#!/bin/bash
#
# Search for a query with google
# Author: Sven Sperner <cethss@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

url="www.google.de/search?q="
cbrowser="links -driver fb"
xbrowser="chromium"
link=$url

for arg in $*
do
	if [ "$link" == "$url" ]
	then
		link="$link$arg"
	else
		link="$link+$arg"
	fi
done

case "$TERM" in
	"linux")	$cbrowser "$link";;
	"xterm")	$xbrowser "$link";;
esac
